### ISSUE TITLE
Твой код из примера не работает.

### ISSUE THREAD

**Issue by crazyk2** [Sudalius/YandexMarketTest#2]
`        String searchResult = $(By.cssSelector(".n-product-title > h1:nth-child(1)")).getText();
`Такого локатора нет на яндексе.
А вот такой есть `.n-product-title h1`.

Код проверяет совсем не то, что предполагалось. Вместо LG и Samsung, сейчас выбирается Philips и что-то еще.
Что нужно сделать, чтобы код теста выбирал именно то, что нужно?

Далее. если ты выбрал для примера Paje Object, то что делает локатор в методе, например,  `String searchResult = $(By.cssSelector(".n-product-title > h1:nth-child(1)")).getText();`? Вопросов в общем много.

**Comment by Sudalius** [comment]
Я проект проверял примерно пару недель назад. Возможно, какие-то селекторы и поменялись.
Поле "результат поиска" - согласен, можно было вынести в отдельный элемент. Не предал почему-то этому значения.
Что Вы имели в виду под фразой "Вопросов в общем много"?

**Comment by Sudalius** [comment]
Так или иначе, данный код - это скорее пример того, как я проектирую свои тесты и какие технологии переменяю, нежели чем рабочий пример для практики

**Comment by crazyk2** [comment]
Я рассматривал Ваш код, потому что меня попросили его оценить как код кандидата на должность, поэтому и написал, что некоторые вещи стоит переделать, улучшить, поправить. В том то и дело, что Ваши тесты (даже для примера) не работают уже при малейшем изменении на сайте яндекса и есть способы, позволяющие продолжать твоим тестам отрабатывать как положено, даже после изменения сайта. И вопросов действительно много, но теперь смысла их обсуждать я не вижу, так как Вы отказались от вакансии. Спасибо.
